import type { NextPage } from 'next'
import Head from 'next/head'
import Header from '../components/Header'
import Hero from '../components/Hero'
import Image from "next/image";
import { GeistSans } from 'geist/font/sans'
import { GeistMono } from 'geist/font/mono'
import About from '../components/About';
import TokenAllocation from '../components/TokenAllocation';
import Roadmap from '../components/Roadmap';
import TokenUtility from '../components/TokenUtility';
import FAQ from '../components/FAQ';
import { Toaster } from 'react-hot-toast';
import UseCase from '../components/UseCase';
import Gallery from '../components/Gallery';

const geistSansFont = GeistSans.className
const geistMonoFont = GeistMono.className

const Home: NextPage = () => {
  return (
    <div className={`${geistSansFont} ${geistMonoFont}`}>
      <Head>
        <title>THE  OFFICIAL ELON MEME</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Header />
        <Hero />
        <About />
        <UseCase />
        <Gallery />
        <TokenAllocation />
        <TokenUtility />
        <Roadmap />
        <FAQ />
      </main>
      <Toaster
  position="top-center"
  reverseOrder={false}
/>
    </div>
  )
}

export default Home
